config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "/fetch_month", to: "home#by_month", as: "fetch_month"

  devise_for :users
  resources :favorite_events, only: [:create, :destroy]
  resources :favorite_teams, only: [:create, :destroy]
  resources :favorite_players, only: [:create, :destroy]

  get "/users/", to: "users#index", as: "users"
  get "/users/:id", to: "users#show", as: "user"

  get "/events", to: "events#index", as: "events"
  get "/events/admin", to: "events#admin", as: "events_admin"
  get "/events/new", to: "events#new", as: "new_event"
  post "/events", to: "events#create", as: "create_event"
  get "/events/:id", to: "events#show", as: "event"
  get "/events/:id/edit", to: "events#edit", as: "edit_event"
  patch "/events/:id", to: "events#update", as: "update_event"
  delete "/events/:id", to: "events#destroy", as: "destroy_event"
  match "search" => "events#search", via: [:get, :post], as: :search # route for ransack search

  get "/teams", to: "teams#index", as: "teams"
  get "/teams/new", to: "teams#new", as: "new_team"
  get "/teams/:id", to: "teams#show", as: "team"
  post "/teams", to: "teams#create", as: "create_team"
  get "/teams/:id/edit", to: "teams#edit", as: "edit_team"
  patch "/teams/:id", to: "teams#update", as: "update_team"
  delete "/teams/:id", to: "teams#destroy", as: "destroy_team"

  get "/players", to: "players#index", as: "players"
  get "/players/new", to: "players#new", as: "new_player"
  get "/players/:id", to: "players#show", as: "player"
  post "/players", to: "players#create", as: "create_player"
  get "/players/:id/edit", to: "players#edit", as: "edit_player"
  patch "/players/:id", to: "players#update", as: "update_player"
  delete "/players/:id", to: "players#destroy", as: "destroy_player"

  get "/events/:event_id/teams/new", to: "event_teams#new", as: "add_team_select"
  post "/events/:event_id/teams", to: "event_teams#create", as: "add_team"
  delete "/events/:event_id/teams/:id", to: "event_teams#destroy", as: "delete_team"

  get "/teams/:team_id/players/new", to: "team_players#new", as: "add_player_select"
  post "/teams/:team_id/players", to: "team_players#create", as: "add_player"
  delete "/teams/:team_id/players/:id", to: "team_players#destroy", as: "delete_player"

  match "*path" => redirect("/"), via: :all # route to redirect users to root if they enter invalid URL


end

app/models/user.rb
class User < ApplicationRecord
  has_many :events
  has_many :favorites
  has_many :favorite_events, through: :favorites, source: :favorited, source_type: 'Event'
  has_many :favorite_teams, through: :favorites, source: :favorited, source_type: 'Team'
  has_many :favorite_players, through: :favorites, source: :favorited, source_type: 'Player'

  validates :photo, allow_blank: true, format: { with: %r{.(gif|jpg|png)\Z}i, message: ': must be a URL for GIF, JPG or PNG image.' }
  validates :cover_photo, allow_blank: true, format: { with: %r{.(gif|jpg|png)\Z}i, message: ': must be a URL for GIF, JPG or PNG image.' }
  # validates :twitter, allow_blank: true, format: { with: #enter regexp here, message: ': just the username please'}
  # validates :instagram, allow_blank: true,


  extend FriendlyId
  friendly_id :username, use: :slugged

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, :presence=>true, :uniqueness=>true
  validates :email, :twitter, :instagram, :country, :uniqueness=>true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_admin, only: [:index]

  # get "/users/", to: "users#index", as: "users"
  def index
    @users = User.all
  end

  # get "/users/:id", to: "users#show", as: "user"
  def show
    set_user
    @fav_events = @user.favorite_events
    @fav_teams = @user.favorite_teams
    @fav_players = @user.favorite_players
  end

  private

  def set_user
    @user = User.friendly.find(params[:id])
  end

  def require_admin
    if current_user.nil? || current_user.admin? == false
      redirect_back(fallback_location: root_path) #redirect user to previous page
      flash[:notice] = "Error, you must be an admin"
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="col-sm-10 col-sm-offset-1">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-0 col-xs-6">
      <div class="field">
        <%= f.text_field :username, autofocus: true %>
        <%= f.label :username %>
      </div>

      <div class="field">
        <%= f.email_field :email %>
        <%= f.label :email %>
      </div>

      <% if @current_user.nil? %>
        <div class="field pw">
          <% if @minimum_password_length %>
          <% end %>
          <%= f.password_field :password, autocomplete: "off" %>
          <%= f.label :password %>
          <span class="parenthesis">(<%= @minimum_password_length %> characters minimum)</span>
        </div>
        <div class="field pw">
          <%= f.password_field :password_confirmation, autocomplete: "off" %>
          <%= f.label :password_confirmation %>
        </div>
      <% else %>
        <div class="field">
          <%= f.password_field :current_password, autocomplete: "off" %>
          <%= f.label :current_password %><br />
        </div>
      <% end%>

    </div>

    <div class="col-sm-4 col-sm-offset-0 col-xs-6">
      <div class="field">
        <%= f.text_field :first_name %>
        <%= f.label :first_name %>
      </div>

      <div class="field">
        <%= f.text_field :last_name %>
        <%= f.label :last_name %>
      </div>
      <div class="photo">
        <div class="field">
          <%= f.text_field :photo %>
          <%= f.label :photo %> <span class="parenthesis">(enter URL)</span>
        </div>

        <div class="field">
          <%= f.text_field :cover_photo %>
          <%= f.label :cover_photo %><span class="parenthesis">(enter URL)</span>
        </div>
      </div>

    </div>

    <div class="col-sm-4 col-sm-offset-0 col-xs-6">
      <div class="field">
        <%= f.country_select :country %>
        <%= f.label :country %>
      </div>

      <div class="socials">
        <div class="field">
          <%= f.text_field :twitter %>
          <%= f.label :twitter %><span class="parenthesis"> (enter @username)</span>
        </div>

        <div class="field">
          <%= f.text_field :instagram %>
          <%= f.label :instagram %><span class="parenthesis"> (enter @username)</span>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2 col-sm-offset-5 col-xs-8 col-xs-offset-2">
      <div class="actions">
        <%= f.submit "Submit" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4 col-xs-8 col-xs-offset-2 cancel">
      <% if @current_user %>
        <%= link_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete, class: "delete" %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>List of Registered Users</h1>

<% @users.each do |user| %>
  <ul style="list-style: none;">
    <li>
      <%= link_to user.username, user %>
      since: <%= user.created_at.strftime("%B %-d, %Y") %>
    </li>
  </ul>
<% end %>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="profile col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
      <div class="cover">
        <%= image_tag @user.cover_photo, id:"cover" if @user.cover_photo? %>
        <%= image_tag @user.photo, id:"photo" if @user.photo? %>
        <% if !current_user.nil? && current_user == @user %>
          <%= button_to "Update", edit_user_registration_path(@user), :method => "get" %>
        <% end %>
      </div>
      <div class="row">
        <div class="col-xs-8 col-xs-offset-4">
          <div class="info">
            <span class="admin">
              <% if signed_in? && current_user.admin? %>
                <i class="glyphicon glyphicon-star"></i>
              <% end %>
            </span>
            <%= @user.username %>
          </div> <!-- info -->
        </div>
      </div>
      <div class="row">
        <div class="col-sm-5 col-xs-10 col-xs-offset-1 left-info">
          <div class="country">
            <i class="glyphicon glyphicon-map-marker"></i>
            <%= @user.country %>
          </div>
          <div class="signed-in">
            Last signed in <%= time_ago_in_words(@user.last_sign_in_at) %> ago
          </div>
          <div class="created-at">
            Member since <%= @user.created_at.strftime("%B %-d, %Y") %>
          </div>
          <div class="socials">
            <div class="twitter">
              <span class="fa fa-twitter"></span>
              <% if @user.twitter? %>
                <a href="https://twitter.com/<%=@user.twitter%>"><%= @user.twitter %></a>
              <% end %>
            </div>
            <div class="insta">
              <span class="fa fa-instagram"></span>
              <% if @user.instagram? %>
                <a href="https://www.instagram.com/<%=@user.instagram%>"><%= @user.instagram %></a>
              <% end %>
            </div>
          </div>
          <div class="admin">
            <% if signed_in? && current_user.admin? %>
              <p>Admin Tools:</p>
              <ul>
                <li><%= link_to "Manage Events", events_admin_path %></li>
                <li><%= link_to "Manage Teams", teams_path %></li>
                <li><%= link_to "Manage Players", players_path %></li>
              </ul>
            <% end %>
          </div>
        </div>
        <div class="col-sm-6 col-sm-offset-0 col-xs-10 col-xs-offset-1">
          <div class="fav">
            <u>Favorite Events</u>
            <% @fav_events.each do |event| %>
              <li><%= link_to event.name, event %></li>
            <% end %>
          </div>
          <div class="fav">
            <u>Favorite Teams</u>
            <% @fav_teams.each do |team| %>
              <li><%= link_to team.name, team%></li>
            <% end %>
          </div>
          <div class="fav">
            <u>Favorite Players</u>
            <% @fav_players.each do |player| %>
              <li><%= link_to player.gamer_tag, player%></li>
            <% end %>
          </div>
        </div>
      </div>

    </div>
  </div>

</div>