config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "/fetch_month", to: "home#by_month", as: "fetch_month"

  devise_for :users
  resources :favorite_events, only: [:create, :destroy]
  resources :favorite_teams, only: [:create, :destroy]
  resources :favorite_players, only: [:create, :destroy]

  get "/users/", to: "users#index", as: "users"
  get "/users/:id", to: "users#show", as: "user"

  get "/events", to: "events#index", as: "events"
  get "/events/admin", to: "events#admin", as: "events_admin"
  get "/events/new", to: "events#new", as: "new_event"
  post "/events", to: "events#create", as: "create_event"
  get "/events/:id", to: "events#show", as: "event"
  get "/events/:id/edit", to: "events#edit", as: "edit_event"
  patch "/events/:id", to: "events#update", as: "update_event"
  delete "/events/:id", to: "events#destroy", as: "destroy_event"
  match "search" => "events#search", via: [:get, :post], as: :search # route for ransack search

  get "/teams", to: "teams#index", as: "teams"
  get "/teams/new", to: "teams#new", as: "new_team"
  get "/teams/:id", to: "teams#show", as: "team"
  post "/teams", to: "teams#create", as: "create_team"
  get "/teams/:id/edit", to: "teams#edit", as: "edit_team"
  patch "/teams/:id", to: "teams#update", as: "update_team"
  delete "/teams/:id", to: "teams#destroy", as: "destroy_team"

  get "/players", to: "players#index", as: "players"
  get "/players/new", to: "players#new", as: "new_player"
  get "/players/:id", to: "players#show", as: "player"
  post "/players", to: "players#create", as: "create_player"
  get "/players/:id/edit", to: "players#edit", as: "edit_player"
  patch "/players/:id", to: "players#update", as: "update_player"
  delete "/players/:id", to: "players#destroy", as: "destroy_player"

  get "/events/:event_id/teams/new", to: "event_teams#new", as: "add_team_select"
  post "/events/:event_id/teams", to: "event_teams#create", as: "add_team"
  delete "/events/:event_id/teams/:id", to: "event_teams#destroy", as: "delete_team"

  get "/teams/:team_id/players/new", to: "team_players#new", as: "add_player_select"
  post "/teams/:team_id/players", to: "team_players#create", as: "add_player"
  delete "/teams/:team_id/players/:id", to: "team_players#destroy", as: "delete_player"

  match "*path" => redirect("/"), via: :all # route to redirect users to root if they enter invalid URL


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @events = Event.order(:date)
  end

  # get "/fetch_month", to: "events#by_month", as: "fetch_month"
  def by_month
    # p params[:month]
    @selected = Event.where('extract(month from date) = ?', params[:month].to_i)
    # p @selected
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_event.html.erb
<div class="container-fluid event">

  <% events.each do |event| %>
    <%= render partial: 'home/event_card', locals: { event: event} %>
  <% end %>
</div>

app/views/home/_event_card.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3 col-xs-8 col-xs-offset-2">
    <div class="event-card">
      <div class="name">
        <%= link_to event.name, event %>
      </div>
      <%= image_tag event.image %>
      <div class="card-content">
        <div class="date">
          <%= event.date.strftime("%B %-d") %> - <%= event.date_end.strftime("%B %-d, %Y") %>
        </div>
        <div class="city">
          <%= event.city %>
        </div>
        <div class="favorite">
          <% if signed_in? %>
            <% unless current_user.favorite_events.exists?(id: event) %>
              <%= link_to favorite_events_path(event), method: :post do %>
                <i class="glyphicon glyphicon-heart-empty"></i>
              <% end %>
            <% else %>
              <%= link_to favorite_event_path(event), method: :delete do %>
                <i class="glyphicon glyphicon-heart"></i>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/by_month.js.erb
// to handle front-end changes when respond_to js
// is called (being triggered by remote: true)

// hide index of events
$("#index-events").hide();
$("#cover-video").show();

$("#current-month").html("<%= escape_javascript(render partial: 'home/event', locals: { events: @selected } ) %>");

app/views/home/index.html.erb
<div class="home-page">
  <div class="home-banner">
    <%= video_tag "bg-video.mp4", autoplay: true, loop: true %>

    <div class="arrow"></div>

    <div class="month-bar">
      <ul class="grid">
        <!-- <li class="month"><%= link_to "June", fetch_month_path(:month => 6), remote: true %></li> -->
        <li class="month"><%= link_to "July", fetch_month_path(:month => 7), remote: true %></li>
        <li class="month"><%= link_to "August", fetch_month_path(:month => 8), remote: true %></li>
        <li class="month"><%= link_to "September", fetch_month_path(:month => 9), remote: true %></li>
        <li class="month"><%= link_to "October", fetch_month_path(:month => 10), remote: true %></li>
        <li class="month"><%= link_to "November", fetch_month_path(:month => 11), remote: true %></li>
      </ul>
    </div> <!-- month-bar -->
  </div>

  <div id="index-events" class="container-fluid">
    <% @events.each do |event| %>
      <%= render partial: 'home/event_card', locals: { event: event} %>
    <% end %>
  </div>

  <!-- partial _event will render here  -->
  <div id="current-month">
  </div>

</div>