config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "/fetch_month", to: "home#by_month", as: "fetch_month"

  devise_for :users
  resources :favorite_events, only: [:create, :destroy]
  resources :favorite_teams, only: [:create, :destroy]
  resources :favorite_players, only: [:create, :destroy]

  get "/users/", to: "users#index", as: "users"
  get "/users/:id", to: "users#show", as: "user"

  get "/events", to: "events#index", as: "events"
  get "/events/admin", to: "events#admin", as: "events_admin"
  get "/events/new", to: "events#new", as: "new_event"
  post "/events", to: "events#create", as: "create_event"
  get "/events/:id", to: "events#show", as: "event"
  get "/events/:id/edit", to: "events#edit", as: "edit_event"
  patch "/events/:id", to: "events#update", as: "update_event"
  delete "/events/:id", to: "events#destroy", as: "destroy_event"
  match "search" => "events#search", via: [:get, :post], as: :search # route for ransack search

  get "/teams", to: "teams#index", as: "teams"
  get "/teams/new", to: "teams#new", as: "new_team"
  get "/teams/:id", to: "teams#show", as: "team"
  post "/teams", to: "teams#create", as: "create_team"
  get "/teams/:id/edit", to: "teams#edit", as: "edit_team"
  patch "/teams/:id", to: "teams#update", as: "update_team"
  delete "/teams/:id", to: "teams#destroy", as: "destroy_team"

  get "/players", to: "players#index", as: "players"
  get "/players/new", to: "players#new", as: "new_player"
  get "/players/:id", to: "players#show", as: "player"
  post "/players", to: "players#create", as: "create_player"
  get "/players/:id/edit", to: "players#edit", as: "edit_player"
  patch "/players/:id", to: "players#update", as: "update_player"
  delete "/players/:id", to: "players#destroy", as: "destroy_player"

  get "/events/:event_id/teams/new", to: "event_teams#new", as: "add_team_select"
  post "/events/:event_id/teams", to: "event_teams#create", as: "add_team"
  delete "/events/:event_id/teams/:id", to: "event_teams#destroy", as: "delete_team"

  get "/teams/:team_id/players/new", to: "team_players#new", as: "add_player_select"
  post "/teams/:team_id/players", to: "team_players#create", as: "add_player"
  delete "/teams/:team_id/players/:id", to: "team_players#destroy", as: "delete_player"

  match "*path" => redirect("/"), via: :all # route to redirect users to root if they enter invalid URL


end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user, optional: true
  has_many :event_teams, dependent: :destroy
  has_many :teams, through: :event_teams

  validates :name, :presence=>true, :uniqueness=>true
  validates :organizer, :date, :date_end, :venue, :city, :country, :image, :stream, :tickets, :presence=>true

  extend FriendlyId
  friendly_id :name, use: [:slugged]

  geocoded_by :venue
  after_validation :geocode

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_admin, only: [:new, :create, :edit, :update, :destroy, :admin]
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :load_tweets, only: [:show]

  # match "search" => "events#search", via: [:get, :post], as: :search # route for ransack search
  def search
    index
    render :index
  end

  # get "/events/admin", to: "events#admin", as: "events_admin"
  def admin
    @events = Event.all
  end

  # get "/events", to: "events#index", as: "events"
  def index
    @q = Event.ransack(params[:q])
    @events = @q.result
    @hash = Gmaps4rails.build_markers(@events) do |event, marker|
      event_path = view_context.link_to event.name, event_path(event)
      marker.lat event.latitude
      marker.lng event.longitude
      marker.title event.name
      marker.infowindow render_to_string(:partial => "/events/info",
        :locals => { :event => event}) # allows use of |event| in partial
    end
  end

  # get "/events/new", to: "events#new", as: "new_event"
  def new
    @event = Event.new
  end

  # post "/events", to: "events#create", as: "create_event"
  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:notice] = "Success, event successfully created"
      redirect_to events_path
    else
      flash[:notice] = @event.errors.full_messages.join(" ")
      redirect_to new_event_path
    end
  end

  # get "/events/:id", to: "events#show", as: "event"
  def show
  end

  # get "/events/:id/edit", to: "events#edit", as: "edit_event"
  def edit
  end

  # patch "/events/:id", to: "events#update", as: "update_event"
  def update
    @event.update_attributes(event_params)
    flash[:notice] = "Success, event was updated"
    redirect_to event_path(@event)
  end

  # delete "/events/:id", to: "events#destroy", as: "destroy_event"
  def destroy
    if current_user.try(:admin?)
      @event.destroy
      redirect_to events_path
    else
      flash[:notice] = "Error, you need admin status"
      redirect_to events_admin_path
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :organizer, :date, :venue,
      :min_age, :stream, :tickets, :size, :organizer_twitter, :stadium, :vip_tickets,
      :food_drinks, :merch_sold, :city, :country, :date_end, :event_type, :prize, :image, :ticket_price, :alcohol, :slug)
  end

  def set_event
    @event = Event.friendly.find(params[:id])
  end

  def require_admin
    if current_user.nil? || current_user.admin? == false
      redirect_back(fallback_location: root_path) #redirect user to previous page
      flash[:notice] = "Error, you must be an admin"
    end
  end

  def load_tweets
    @tweets = $client.user_timeline(@event.organizer_twitter, count:5)
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="container-fluid event-form">
  <div class="row">
    <div class="col-md-3 col-md-offset-0 col-md-offset-1 col-xs-8 col-xs-offset-2">
      <%= f.text_field :name %>
      <p>Event Name</p>
      <%= f.text_field :organizer %>
      <p>Organizer</p>
      <%= f.date_field :date %>
      <p>Start Date</p>
      <%= f.date_field :date_end %>
      <p>End Date</p>
      <%= f.text_field :city %>
      <p>City</p>
    </div>
    <div class="col-md-3 col-md-offset-0 col-xs-8 col-xs-offset-2">
      <%= f.text_field :country %><br />
      <p>Country </p>
      <%= f.text_field :venue %><br />
      <p>Venue </p>
      <%= f.select :event_type, ['minor', 'big', 'major'] %>
      <p>Event Type </p>
      <%= f.text_field :prize %>
      <p>Prize </p>
      <%= f.text_field :image %>
      <p>Image </p>
    </div>
    <div class="col-md-3 col-md-offset-0 col-xs-8 col-xs-offset-2">
      <%= f.text_field :min_age %>
      <p>Minimum Age </p>
      <%= f.text_field :stream %>
      <p>Stream Link </p>
      <%= f.text_field :tickets %>
      <p>Tickets </p>
      <%= f.text_field :ticket_price %>
      <p>Ticket Price </p>
    </div>
    <div class="col-md-2 col-md-offset-0 col-xs-8 col-xs-offset-2" id="booleans">
      <p>Stadium <%= f.check_box :stadium %></p>

      <p>VIP Tix sold? <%= f.check_box :vip_tickets %></p>

      <p>Food Drink sold? <%= f.check_box :food_drinks %></p>

      <p>Alcohol sold? <%= f.check_box :alcohol %></p>

      <p>Merch sold? <%= f.check_box :merch_sold %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 col-md-offset-4 col-xs-6 col-xs-offset-3">
      <%= f.submit "Save" %>
    </div>
  </div>

</div>

app/views/events/_info.html.erb
<div id="iw-container">
  <div class="iw-title"> <%= link_to event.name, event_path(event) %> </div>
  <div class="iw-content">
    <p><%= event.date.strftime("%B %-d") %> - <%= event.date_end.strftime("%B %-d, %Y") %></p>
    <p class="city"><%= event.city %></p>
  </div>
</div>

app/views/events/_search_card.html.erb
<div class="search-result">
  <div class="name">
    <h3><%= link_to event.name, event %></h3>
  </div>
  <div class="favorite">
    <% if signed_in? %>
      <% unless current_user.favorite_events.exists?(id: event) %>
        <%= link_to favorite_events_path(event), method: :post do %>
          <i class="glyphicon glyphicon-heart-empty"></i>
        <% end %>
      <% else %>
        <%= link_to favorite_event_path(event), method: :delete do %>
          <i class="glyphicon glyphicon-heart"></i>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="dates">
    <%= event.date.strftime("%B %-d") %> - <%= event.date_end.strftime("%B %-d, %Y") %>
  </div>
  <div class="city">
    <%= event.venue %> in <%= event.city %>
  </div>
  <div class="prize">
    Prize Pool: $<%= event.prize %>
  </div>
  <div class="other">
    <p>Minimum Age for Entry: <%= event.min_age %></p>
    <a href="<%=event.tickets%>">Buy Tickets!</a>
    <p><a href="<%=event.stream%>">Watch on Stream</a></p>
  </div>
  <div class="admin">
    <% if signed_in? && current_user.admin? %>
      Admin Tools:
      <%= link_to "edit event", edit_event_path(event) %>
    <%end%>
  </div>
</div>

<!-- <%= image_tag event.image %> -->

app/views/events/admin.html.erb
<div class="container-fluid event-admin">
  <h1>Manage Events</h1>
  <%= link_to "Create New Event", new_event_path %>

  <div class="row">
    <div class="col-xs-12">
      <% @events.each do |event| %>
        <p>
          <%= event.name %>:
          <%= link_to "View", event_path(event) %>
          <%= link_to edit_event_path(event) do %>
            <i class="glyphicon glyphicon-pencil"></i>
          <% end %>
          <%= link_to destroy_event_path(event), data: {confirm: "Are you sure you want to delete?"}, method: :delete do %>
            <i class="glyphicon glyphicon-trash"></i>
          <% end %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<div class="edit-event">
  <h1>Edit Event</h1>
  
  <%= form_for @event, :url => { :action => "update" } do |f| %>
    <%= render partial: 'events/form', locals: { f: f } %>
  <% end %>

  <div class="container-fluid">
    <div class="row teams">
      <div class="col-md-4 col-md-offset-4 col-xs-6 col-xs-offset-3">
        <h4>Team List (<%= link_to "add a team", add_team_select_path(@event) %>)</h4>
        <% @event.teams.each do |team| %>
          <%= team.name %> |
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyBHLett8djBo62dDXj0EjCimF8Rd6E8cxg"> </script> <!-- this is general use API key from geoquakes -->
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>

<div class="container-fluid event-index">
  <div class="row mapped">
    <div class="col-md-4 search">
      <h4>Search for your next event!</h4>
      <%= search_form_for @q do |f| %>
        <p>Enter Name, Organizer, or Location!</p>
        <%= f.search_field :name_or_organizer_or_venue_or_city_or_country_cont %>
        <div class="dates">
          <p>Happening between:</p>
          <span>Start </span>
          <%= f.date_select :date_gteq, :start_year => 2017, include_hidden: false, include_blank: true %><br/>
          <span class="end">End  </span>
          <%= f.date_select :date_end_lteq, :start_year => 2017, include_hidden: false, include_blank: true %>
        </div>
        <div class="type">
          Event Type
          <%= f.select :event_type_eq, ['minor', 'large', 'major'], include_hidden: false, include_blank: true %>
        </div>
        <div class="prize">
          Prize Pool At Least...
          <%= f.text_field :prize_gteq, include_hidden: false %>
        </div>
        <div class="age">
          Minimum Age for Entry...
          <%= f.text_field :min_age_lteq, include_hidden: false %>
        </div>
        <%= f.label "Stadium" %>
        <%= f.check_box :stadium_true, include_hidden: false %><br />
        <%= f.label "Food & Drinks Sold" %>
        <%= f.check_box :food_drinks_true, include_hidden: false %><br />
        <%= f.label "VIP Tickets" %>
        <%= f.check_box :vip_tickets_true, include_hidden: false %><br />
        <%= f.label "Merch Sold" %>
        <%= f.check_box :merch_sold_true, include_hidden: false %><br />
        <%= f.label "Alcohol Sold" %>
        <%= f.check_box :alcohol_true, include_hidden: false %><br />
        <%= f.submit %>
      <% end %>
    </div>

    <div class="col-md-7">
      <div id="map" style='width: 700px; height: 400px;'></div>
    </div>

  </div>

  <div class="row">
    <div class="col-sm-6 sort">
      <!-- sorts ransack search results by name -->
      Sory by: <%= sort_link(@q, :date) %> |
      <%= sort_link(@q, :name) %>
    </div>
  </div>

  <div class="row">
    <% @events.each do |event| %>
      <div class="col-sm-4">
        <%= render partial: 'events/search_card', locals: { event: event} %>
      </div>
    <% end %>
  </div>


  <br/>
  <br/>

</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/events/new.html.erb
<div class="new-event">
  <h1>Create New Event</h1>
  <%= link_to "Back", :back%>

  <%= form_for @event, :url => { :action => "create" } do |f| %>
  <%= render partial: 'events/form', locals: { f: f } %>
  <% end %>

</div>

app/views/events/show.html.erb
<div class="container-fluid event-show">
	<div class="row">
		<div class="col-lg-8 col-lg-offset-2 col-xs-10 col-xs-offset-1">
			<div>
				<div class="banner">
					<%= image_tag @event.image, class:"banner" %>
					<h1><%=@event.name%></h1>
				</div>
				<div class="admin">
					<% if signed_in? && current_user.admin? %>
						<p>Admin Tools:
						<%= link_to "edit event", edit_event_path(@event) %>   ||
						<%= link_to "delete event", destroy_event_path(@event), data: { confirm: "Are you sure you want to delete" }, method: :delete %>   ||
						<%= link_to "add a team", add_team_select_path(@event) %>
						</p>
					<% end %>
				</div>
				<%= link_to "Back", :back, class: "back"%><br/><br/>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4 col-md-offset-1 col-xs-10 col-xs-offset-1 left">
			<h3>Recent Tweets from <span class="fa fa-twitter"></span>
				<a href="https://www.twitter.com/<%=@event.organizer%>"><%=@event.organizer%></a>
			</h3>
				<!-- twitter widget -->
			<div class="widget">
				<% hashtag = @event.name.split(' ').join('') %>
				Tweet about it!  <%= link_to "##{hashtag}", "https://twitter.com/intent/tweet?button_hashtag=#{hashtag}", :target => "_blank" %>
			</div>
			<div class="twitter-feed" id="tweets">
				 <% @tweets.each do |tweet| %>
						<div class="tweet-card">
							<%= tweet.text %>
							<div class="tweet-data">
								<span class="blue"><i class="glyphicon glyphicon-retweet"></i> <%= tweet.retweet_count %></span>
								<span class="red"><i class="glyphicon glyphicon-star"></i> <%= tweet.favorites_count %></span>
							</div>
						</div>
				 <% end %>
			</div>
		</div>

		<div class="col-md-6 col-md-push-0 col-xs-10 col-xs-push-1 team-list">
			<h3>Teams Attending:</h3>
			<% @event.teams.each do |team| %>
				<div class="card">
					<div class="row">
						<div class="col-xs-4">
							<%= image_tag team.logo, class: "logo" %>
							<div class="team-info">
								<h4><%= link_to team.name, team %>
									<span class="favorite">
										<% if signed_in? %>
											<% unless current_user.favorite_teams.exists?(id: team) %>
												<%= link_to favorite_teams_path(team), method: :post do %> <i class="glyphicon glyphicon-heart-empty"></i><% end %>
											<% else %>
												<%= link_to favorite_team_path(team), method: :delete do %> <i class="glyphicon glyphicon-heart"></i><% end %>
											<% end %>
										<% end %>
									</span>
								</h4>
								<!-- <p><%= team.country %></p> -->
								<p><span class="fa fa-twitter"></span>
									<% if team.twitter? %>
										<a href="https://www.twitter.com/<%=team.twitter%>"><%= team.twitter %></a>
									<% end %>
								</p>
								<!-- <p>Founded in: <%= team.founded_in %></p> -->
							</div> <!-- team-info -->
						</div>
						<div class="col-xs-8 right">
							<ul style="list-style:none">
								<% team.players.each do |player| %>
									<li> <strong><%= player.gamer_tag %></strong> - <%=player.role %> from <%=player.country %></li>
								<% end %>
							</ul>
							<div class="admin">
								<% if signed_in? && current_user.admin? %>
									<p>Admin Tools: <%= link_to "delete team from event", delete_team_path(@event, team), method: :delete %></p>
								<% end %>
							</div>
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>