config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "/fetch_month", to: "home#by_month", as: "fetch_month"

  devise_for :users
  resources :favorite_events, only: [:create, :destroy]
  resources :favorite_teams, only: [:create, :destroy]
  resources :favorite_players, only: [:create, :destroy]

  get "/users/", to: "users#index", as: "users"
  get "/users/:id", to: "users#show", as: "user"

  get "/events", to: "events#index", as: "events"
  get "/events/admin", to: "events#admin", as: "events_admin"
  get "/events/new", to: "events#new", as: "new_event"
  post "/events", to: "events#create", as: "create_event"
  get "/events/:id", to: "events#show", as: "event"
  get "/events/:id/edit", to: "events#edit", as: "edit_event"
  patch "/events/:id", to: "events#update", as: "update_event"
  delete "/events/:id", to: "events#destroy", as: "destroy_event"
  match "search" => "events#search", via: [:get, :post], as: :search # route for ransack search

  get "/teams", to: "teams#index", as: "teams"
  get "/teams/new", to: "teams#new", as: "new_team"
  get "/teams/:id", to: "teams#show", as: "team"
  post "/teams", to: "teams#create", as: "create_team"
  get "/teams/:id/edit", to: "teams#edit", as: "edit_team"
  patch "/teams/:id", to: "teams#update", as: "update_team"
  delete "/teams/:id", to: "teams#destroy", as: "destroy_team"

  get "/players", to: "players#index", as: "players"
  get "/players/new", to: "players#new", as: "new_player"
  get "/players/:id", to: "players#show", as: "player"
  post "/players", to: "players#create", as: "create_player"
  get "/players/:id/edit", to: "players#edit", as: "edit_player"
  patch "/players/:id", to: "players#update", as: "update_player"
  delete "/players/:id", to: "players#destroy", as: "destroy_player"

  get "/events/:event_id/teams/new", to: "event_teams#new", as: "add_team_select"
  post "/events/:event_id/teams", to: "event_teams#create", as: "add_team"
  delete "/events/:event_id/teams/:id", to: "event_teams#destroy", as: "delete_team"

  get "/teams/:team_id/players/new", to: "team_players#new", as: "add_player_select"
  post "/teams/:team_id/players", to: "team_players#create", as: "add_player"
  delete "/teams/:team_id/players/:id", to: "team_players#destroy", as: "delete_player"

  match "*path" => redirect("/"), via: :all # route to redirect users to root if they enter invalid URL


end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team, optional: true

  extend FriendlyId
  friendly_id :gamer_tag, use: [:slugged]

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :require_admin, only: [:new, :index, :create, :edit, :update, :destroy]
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # get "/players", to: "players#index", as: "players"
  def index
    @players = Player.all
  end

  # get "/players/:id", to: "players#show", as: "player"
  def show
  end

  # get "/players/new", to: "players#new", as: "new_player"
  def new
    @player = Player.new
  end

  # post "/players", to: "players#create", as: "create_player"
  def create
    @player = Player.create(player_params)
    if @player.save
      flash[:notice] = "Success, player successfully created"
      redirect_to players_path
    else
      flash[:error] = @event.errors.full_messages.join(" ")
      redirect_to new_team_path
    end
  end

  # get "/players/:id/edit", to: "players#edit", as: "edit_player"
  def edit

  end

  # patch "/players/:id", to: "players#update", as: "update_player"
  def update
    @player.update_attributes(player_params)
    flash[:notice] = "Success, player was updated"
    redirect_to players_path
  end

  # delete "/players/:id", to: "players#destroy", as: "destroy_player"
  def destroy
    if current_user.try(:admin?)
      @player.destroy
      redirect_to players_path
    else
      flash[:notice] = "Error, you need admin status"
      redirect_to players_path
    end
  end

  private

  def player_params
    params.require(:player).permit(:name, :gamer_tag, :country, :twitter, :instagram, :photo, :role, :slug)
  end

  def set_player
    @player = Player.friendly.find(params[:id])
  end

  def require_admin
    if current_user.nil? || current_user.admin? == false
      redirect_back(fallback_location: root_path) #redirect user to previous page
      flash[:notice] = "Error, you must be an admin"
    end
  end

end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<div class="container-fluid">
  <div class="row player-form">
    <div class="col-xs-6 col-xs-offset-3">
      <%= link_to "Back", :back%>

      <%= f.text_field :name %>
      <p>Full Name</p>
      <%= f.text_field :gamer_tag %>
      <p>Gamer Tag</p>
      <%= f.select :role, ['AWPer', 'Support', 'Entry', 'Rifler', 'IGL']%>
      <p>Role:</p>
      <%= f.text_field :photo %>
      <p>Photo</p>
      <%= f.text_field :twitter %>
      <p>Twitter</p>
      <%= f.text_field :instagram %>
      <p>Instagram</p>
      <br>
      <div class="submit">
        <%= f.submit "Save" %>
      </div>
    </div>
  </div>
</div>

app/views/players/edit.html.erb
<div class="edit-player">
  <h1>Edit Player</h1>

  <%= form_for @player, :url => { :action => "update" } do |f| %>
    <%= render partial: 'players/form', locals: { f: f } %>
  <% end %>
</div>

app/views/players/index.html.erb
<div class="players-index">

  <h1>Manage Players</h1>
  <%= link_to "Create New Player", new_player_path %>

  <% @players.each do |player| %>
    <p>
      <%= player.gamer_tag %>
      <%= link_to edit_player_path(player) do %>
        <i class="glyphicon glyphicon-pencil"></i>
      <% end %>
      <%= link_to destroy_player_path(player), data: { confirm: "Are you sure you want to delete" }, method: :delete do %>
        <i class="glyphicon glyphicon-trash"></i>
      <% end %>
      <% if player.team.nil? %> N/A
        <% else %> <%= link_to player.team.name, player.team %>
      <% end %>

    </p>
  <% end %>
</div>

app/views/players/new.html.erb
<div class="new-player">
  <h1>Create New Player</h1>
  <%= form_for @player, :url => { :action => "create" } do |f| %>
    <%= render partial: 'players/form', locals: { f: f } %>
  <% end %>
</div>

app/views/players/show.html.erb
<div class="player-show">
  <h1><u><%=@player.gamer_tag%></u></h1>

  <p>Name: <%= @player.name %></p>
  <p>Role: <%= @player.role %></p>
  <p>Country: <%= @player.country %></p>
  <p>Team: <%= @player.team.name unless @player.team.nil? %></p>

  <div class="socials">
    <div class="twitter">
      <% if @player.twitter? %>
        <a href="https://twitter.com/<%=@player.twitter%>">
          <img src="https://cdn3.iconfinder.com/data/icons/free-social-icons/67/twitter_circle_black-128.png" alt="">
          <%= @player.twitter %>
        </a>
      <% end %>
    </div>
    <div class="insta">
      <% if @player.instagram? %>
        <a href="https://www.instagram.com/<%=@player.instagram%>">
          <img src="https://cdn4.iconfinder.com/data/icons/picons-social/57/38-instagram-3-128.png" alt="">
          <%= @player.instagram %>
        </a>
      <% end %>
    </div>


  <div class="admin">
    <% if signed_in? && current_user.admin? %>
      <%= link_to edit_player_path(@player) do %>
        <i class="glyphicon glyphicon-pencil"></i>
      <% end %>
      <%= link_to destroy_player_path(@player), data: { confirm: "Are you sure you want to delete" }, method: :delete do %>
        <i class="glyphicon glyphicon-trash"></i>
      <% end %>
    <% end %>
  </div>
</div>